@baseURL = http://localhost:8000/api/v1/account
@apiKey =  1iotop56m-1fa7e3b67a70dd2f10be8537904fc9920e8276f6233ac8609f2bf1f8a74b9113

# @name create_account
POST {{baseURL}}/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@email.com"
}

###

# @name get_account
GET {{baseURL}}/
X-Api-Key: {{apiKey}}